info:
  component: Review Service

server:
  port: ${PORT:9999}
  use-forward-headers: false

logging:
  file: ${user.home}/Downloads/log/review-service.log

---
spring:
  profiles: test

logging:
  file: ${user.home}/ecom-logs/review-service.log

---
spring:
  profiles: cloud

logging:
  file: ${user.home}/ecom-logs/review-service.log